#!/usr/bin/env python

def main(ini_file):
    import subprocess, os, glob
    from pyramid.paster import get_appsettings
    from sqlalchemy import engine_from_config
    from pyvideohub.models import ScopedSession, Base, DBSession, Video

    settings = get_appsettings(ini_file)
    engine = engine_from_config(settings, 'sqlalchemy.')
    ScopedSession.configure(bind=engine)
    Base.metadata.bind = engine

    session = ScopedSession()
    videos = session.query(Video).filter(Video.status == 0).all()
    # 處理轉檔
    for video in videos:
        video_basedir = settings['video.store_path']
        infile  = glob.glob(os.path.join(video_basedir, '{}/{}/tmp-{}.*'.format(video.upload_date.year, video.upload_date.month, video.id)))[0]
        outfile = os.path.join(video_basedir, '{}/{}/{}.mp4'.format(video.upload_date.year, video.upload_date.month, video.id))
        cmd = 'ffmpeg -i "{}" -s 480x320 -vcodec libx264 -strict experimental -y "{}"'.format(infile, outfile)
        result = subprocess.call(cmd, shell=True)
        if result == 0:
            os.remove(infile)
            # 更新 status
            video.status = 1
        session.commit()
    ScopedSession.remove()

if __name__ == '__main__':
    import sys
    main(sys.argv[1])
